// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY7cQ7uZTjVw3pLFvz0a-rY1l2R6TdQkA',
    appId: '1:596710042514:web:54b269a6baf7f38529af4b',
    messagingSenderId: '596710042514',
    projectId: 'app-presupuestos-73542',
    authDomain: 'app-presupuestos-73542.firebaseapp.com',
    storageBucket: 'app-presupuestos-73542.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPa8zvF5s1x7cnxKexXneLR8_baoTKWg',
    appId: '1:596710042514:android:36ea3b31c1e4c96229af4b',
    messagingSenderId: '596710042514',
    projectId: 'app-presupuestos-73542',
    storageBucket: 'app-presupuestos-73542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKP8XqtjCEAVV24tGhHada9KsyQU5teY',
    appId: '1:596710042514:ios:321c0d6e9d8086a429af4b',
    messagingSenderId: '596710042514',
    projectId: 'app-presupuestos-73542',
    storageBucket: 'app-presupuestos-73542.firebasestorage.app',
    iosClientId: '596710042514-spo0ck48ekqfqs3vdd2ng2bgj80i5r4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPresupuestos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvKP8XqtjCEAVV24tGhHada9KsyQU5teY',
    appId: '1:596710042514:ios:321c0d6e9d8086a429af4b',
    messagingSenderId: '596710042514',
    projectId: 'app-presupuestos-73542',
    storageBucket: 'app-presupuestos-73542.firebasestorage.app',
    iosClientId: '596710042514-spo0ck48ekqfqs3vdd2ng2bgj80i5r4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPresupuestos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY7cQ7uZTjVw3pLFvz0a-rY1l2R6TdQkA',
    appId: '1:596710042514:web:4a5d1b80ac5b9a9029af4b',
    messagingSenderId: '596710042514',
    projectId: 'app-presupuestos-73542',
    authDomain: 'app-presupuestos-73542.firebaseapp.com',
    storageBucket: 'app-presupuestos-73542.firebasestorage.app',
  );
}
